// Mocks generated by Mockito 5.4.6 from annotations
// in linkyou_tasks_app/test/task/task_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:linkyou_tasks_app/features/tasks/data/datasources/task_local_datasource.dart'
    as _i6;
import 'package:linkyou_tasks_app/features/tasks/data/datasources/task_remote_datasource.dart'
    as _i4;
import 'package:linkyou_tasks_app/features/tasks/domain/entities/task.dart'
    as _i3;
import 'package:linkyou_tasks_app/features/tasks/domain/entities/task_list.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaskList_0 extends _i1.SmartFake implements _i2.TaskList {
  _FakeTaskList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTask_1 extends _i1.SmartFake implements _i3.Task {
  _FakeTask_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRemoteDataSource extends _i1.Mock
    implements _i4.TaskRemoteDataSource {
  MockTaskRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.TaskList> getTasks({int? limit = 10, int? skip = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, [], {#limit: limit, #skip: skip}),
            returnValue: _i5.Future<_i2.TaskList>.value(
              _FakeTaskList_0(
                this,
                Invocation.method(#getTasks, [], {#limit: limit, #skip: skip}),
              ),
            ),
          )
          as _i5.Future<_i2.TaskList>);

  @override
  _i5.Future<_i3.Task> getTaskById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTaskById, [id]),
            returnValue: _i5.Future<_i3.Task>.value(
              _FakeTask_1(this, Invocation.method(#getTaskById, [id])),
            ),
          )
          as _i5.Future<_i3.Task>);

  @override
  _i5.Future<_i3.Task> addTask(String? todo, bool? completed, int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [todo, completed, userId]),
            returnValue: _i5.Future<_i3.Task>.value(
              _FakeTask_1(
                this,
                Invocation.method(#addTask, [todo, completed, userId]),
              ),
            ),
          )
          as _i5.Future<_i3.Task>);

  @override
  _i5.Future<_i3.Task> updateTask(_i3.Task? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i5.Future<_i3.Task>.value(
              _FakeTask_1(this, Invocation.method(#updateTask, [task])),
            ),
          )
          as _i5.Future<_i3.Task>);

  @override
  _i5.Future<void> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [TaskLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskLocalDataSource extends _i1.Mock
    implements _i6.TaskLocalDataSource {
  MockTaskLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i3.Task>> getCachedTasks() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedTasks, []),
            returnValue: _i5.Future<List<_i3.Task>>.value(<_i3.Task>[]),
          )
          as _i5.Future<List<_i3.Task>>);

  @override
  _i5.Future<void> cacheTasks(List<_i3.Task>? tasks) =>
      (super.noSuchMethod(
            Invocation.method(#cacheTasks, [tasks]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
